import {clip,median,interp,smooth1d} from './numeric.js';
import {raster,blur,polygon} from './cv.js';
const blurred=(data,w,h,sx,sy)=>blur(raster(w,h,1,data),Math.max(.5,sx),Math.max(.5,sy),cv.BORDER_CONSTANT).data;
const P={side_plane_lift:.217,end_center_fraction:.361,end_width_fraction:.488,end_center_drop:.122,end_ground_spill:.055,end_tilt_fraction:.035,core_opacity:.897,core_blur_x:.209,core_blur_y:.076,ambient_opacity:.045};

function oblique(w,h,g){const [left,right]=[g.contacts[0],g.contacts.at(-1)],[x0,,x1]=g.bbox,lg=left.x-x0,rg=x1-right.x,endLeft=lg>rg,near=endLeft?left:right,overhang=endLeft?lg:rg,dir=endLeft?-1:1,r=near.radius,profile=g.lower_body_profile,xs=profile.map(p=>p[0]),ys=profile.map(p=>p[1]),slope=(right.y-left.y)/Math.max(1,right.x-left.x),[shiftX,shiftY]=g.view_cues.opposite_track_shift;
  const valid=profile.filter(p=>dir*(p[0]-near.x)>.30*overhang&&dir*(p[0]-near.x)<.84*overhang),bumper=valid.length?median(valid.map(p=>p[1])):near.y-.6*r,cx=near.x+dir*overhang*P.end_center_fraction,cy=bumper+r*P.end_center_drop,rx=Math.max(r,overhang*P.end_width_fraction),ry=clip(near.y+r*P.end_ground_spill-cy,r*.30,r*.95),tilt=P.end_tilt_fraction*shiftY/(Math.abs(shiftX)>1?shiftX:dir),end=new Float32Array(w*h),support=new Float32Array(w*h);
  for(let x=0;x<w;x++){const lower=interp(x,xs,ys),plane=left.y+slope*(x-left.x)+shiftY*P.side_plane_lift,top=lower-.18*r,extension=.18*r,taper=clip(Math.min(x-left.x+extension,right.x+extension-x)/Math.max(1,.4*r));for(let y=0;y<h;y++){const i=y*w+x,band=y>=top&&y<=plane&&x>=left.x-extension&&x<=right.x+extension?taper:0,d=Math.hypot((x-cx)/rx,(y-cy-tilt*(x-cx))/ry),edge=clip((d-.93)/.12);end[i]=1-edge*edge*(3-2*edge);support[i]=1-(1-band)*(1-end[i]);}}
  return {support,end,r};
}

export function renderShadows(w,h,g){
  const contacts=g.contacts,r=median(contacts.map(c=>c.radius)),[x0,y0,x1,y1]=g.bbox,bw=x1-x0,bh=y1-y0,fp=g.chassis_footprint.map(p=>p.slice()),endOn=g.view_cues.support_mode==='occluded_axle_pair';fp[0][1]+=r*(endOn?.52:.08);fp[1][1]+=r*(endOn?.52:.08);
  const core=polygon(fp,w,h).data,apron=new Float32Array(w*h),profile=g.lower_body_profile,px=profile.map(p=>p[0]),py=profile.map(p=>p[1]),left=contacts[0],right=contacts.at(-1),slope=(right.y-left.y)/Math.max(1,right.x-left.x);
  const xs=Array.from({length:Math.max(0,Math.min(w,Math.trunc(px.at(-1))+1)-Math.max(0,Math.ceil(px[0])))},(_,i)=>i+Math.max(0,Math.ceil(px[0]))),lower=xs.map(x=>interp(x,px,py)),us=xs.map(x=>(x-(left.x+right.x)/2)/Math.max(1,(right.x-left.x)*.55));
  let plane=xs.map((x,i)=>{let p=left.y+slope*(x-left.x);if(x<left.x||x>right.x)p=Math.min(p,lower[i]+r*.32);return p+(endOn?r*.63*Math.sqrt(Math.max(0,1-us[i]*us[i])):r*.035);});plane=smooth1d(plane,Math.max(1,r*.10));
  for(let i=0;i<xs.length;i++){if(lower[i]<Math.max(y0+.63*bh,Math.min(...contacts.map(c=>c.y))-r*.45)||(endOn&&Math.abs(us[i])>1))continue;const density=endOn?1:clip(Math.min(xs[i]-x0,x1-xs[i])/Math.max(1,r*.70));for(let y=Math.max(0,Math.ceil(lower[i]-r*.18));y<=Math.min(h-1,Math.floor(plane[i]));y++)apron[y*w+xs[i]]=density;}
  const support=Float32Array.from(core,(c,i)=>1-(1-c*.68)*(1-apron[i]));let under=Float32Array.from(blurred(support,w,h,r*.13,r*(endOn?.18:.09)),v=>v*.86),broad=Float32Array.from(blurred(support,w,h,r*.52,r*(endOn?.48:.24)),v=>v*.32),endLayer=new Float32Array(w*h);
  let obliqueWeight=endOn?0:clip((g.view_cues.perspective_score-.15)/.55)*clip((Math.abs(g.view_cues.contact_slope)-.035)/.06);
  if(obliqueWeight>0){const q=oblique(w,h,g),cq=blurred(q.support,w,h,q.r*P.core_blur_x,q.r*P.core_blur_y),bq=blurred(q.support,w,h,q.r*.52,q.r*.24),eq=blurred(q.end,w,h,q.r*P.core_blur_x,q.r*P.core_blur_y);for(let i=0;i<under.length;i++){under[i]=under[i]*(1-obliqueWeight)+cq[i]*P.core_opacity*obliqueWeight;broad[i]=broad[i]*(1-obliqueWeight)+bq[i]*P.ambient_opacity*obliqueWeight;endLayer[i]=eq[i]*P.core_opacity*obliqueWeight;}}
  const side=endOn?0:clip((g.view_cues.side_on_score-.55)/.20)*clip((.06-Math.abs(g.view_cues.contact_slope))/.025);
  if(side>0){const lows=Array.from({length:w},(_,x)=>interp(x,px,py));let bottom=lows.map((low,x)=>{const rounding=1-clip(Math.min(x-x0,x1-x)/Math.max(1,1.1*r));let p=left.y+slope*(x-left.x)-.08*r-.38*r*rounding**2;if(x<left.x||x>right.x)p=Math.min(p,low+.24*r);return p;});bottom=smooth1d(bottom,Math.max(1,r*.16));const band=new Float32Array(w*h);for(let x=0;x<w;x++){const top=Math.min(lows[x]-.16*r,bottom[x]-.25*r),edge=clip(Math.min(x-x0,x1-x)/Math.max(1,.95*r)),value=edge*edge*(3-2*edge);for(let y=Math.max(0,Math.ceil(top));y<=Math.min(h-1,Math.floor(bottom[x]));y++)band[y*w+x]=value;}const sc=blurred(band,w,h,r*.19,r*.10),sg=blurred(band,w,h,r*.48,r*.22);for(let i=0;i<under.length;i++){under[i]=under[i]*(1-side)+.92*sc[i]*side;broad[i]=broad[i]*(1-side)+.18*sg[i]*side;}}
  const tire=new Float32Array(w*h);for(const c of contacts){const sx=Math.max(c.half_width*1.2,c.radius*.27,.5),sy=Math.max(1,c.radius*.065);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,local=.86*Math.exp(-.5*(((x-c.x)/sx)**2+((y-c.y-.5)/sy)**2));tire[i]=1-(1-tire[i])*(1-local);}}
  return {tire_contact:tire,underbody:under,ground:broad,end_footprint:endLayer,combined:Float32Array.from(tire,(t,i)=>clip(1-(1-under[i])*(1-broad[i])*(1-t),0,.97))};
}
